// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Readiness is the answer to "can this model generate right now without a
 * hidden multi-GB download?".
 */
export interface Readiness {
    "baseRepo": string;

    /**
     * HasManifest=false means the check COULDN'T run (no base repo, CDN
     * disabled, repo not mirrored). The caller must NOT gate generation then —
     * the engine's lazy path still works, it's just slower on first run.
     */
    "hasManifest": boolean;
    "ready": boolean;
    "totalFiles": number;
    "missingFiles": number;

    /**
     * Sum of the missing files' sizes (HEAD Content-Length); best-effort — a
     * file whose size can't be probed contributes 0, so treat this as "at
     * least" for display.
     */
    "missingBytes": number;
}
