// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound facade. Every method on *App becomes a
 * `window.go.main.App.X(...)` Promise-returning function in the frontend,
 * with TypeScript types auto-generated under frontend/wailsjs/.
 * 
 * All persistent state lives in the five substructs (settings, sidecar,
 * cloud, installer, bus). App's job is to wire requests + emit status events;
 * it owns no business logic.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logbus$0 from "./internal/logbus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";

/**
 * CheckForUpdate asks GitHub for the latest release and compares it to this
 * build. Local "dev" builds return UpdateAvailable=false without any network
 * call. The frontend treats an error as "no banner" — never blocking startup.
 */
export function CheckForUpdate(): $CancellablePromise<types$0.UpdateInfo> {
    return $Call.ByID(2347956003);
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1566804265);
}

/**
 * DeleteSavedImage removes one file from the output folder. Destructive — the
 * renderer confirms first.
 */
export function DeleteSavedImage(name: string): $CancellablePromise<void> {
    return $Call.ByID(1743119110, name);
}

/**
 * DetectPython runs the same probe the installer will use, but on demand —
 * the SettingsDialog calls this to surface "Python X.Y.Z found at …" before
 * the user even clicks Install.
 */
export function DetectPython(): $CancellablePromise<types$0.PythonInfo> {
    return $Call.ByID(425866076);
}

/**
 * ExportWalletPrivateKey returns the raw hex private key so the user
 * can back it up. The renderer must gate this behind a confirmation
 * modal — once this method returns, the secret is in the renderer's
 * memory (and the user's clipboard if they copy it). NEVER LOGGED here.
 */
export function ExportWalletPrivateKey(): $CancellablePromise<string> {
    return $Call.ByID(2656428036);
}

/**
 * GalleryFacets returns the distinct filterable values across the whole gallery
 * (with counts), for building the filter UI.
 */
export function GalleryFacets(): $CancellablePromise<types$0.GalleryFacets> {
    return $Call.ByID(2527262001);
}

/**
 * GenerateCloud is the only HTTP surface to imference.com. Frontend never
 * touches the network directly — keeps auth-key/wallet handling in Go and
 * gives us a single point to add retries / progress events later.
 * 
 * Dispatches based on settings.PaymentMode:
 *   - "x402"   : signs each request with the local wallet (Base mainnet USDC)
 *   - default  : "bearer" — uses settings.APIKey
 */
export function GenerateCloud(req: types$0.GenerationRequest): $CancellablePromise<types$0.GenerationResult> {
    return $Call.ByID(2634479375, req);
}

/**
 * GenerateLocal dispatches to the running Python sidecar. The sidecar
 * itself is single-threaded (the Engine is stateful) so concurrent calls
 * queue up server-side; that's intentional for the POC.
 */
export function GenerateLocal(req: types$0.GenerationRequest): $CancellablePromise<types$0.GenerationResult> {
    return $Call.ByID(3761455137, req);
}

/**
 * GenerateWallet creates a fresh keypair, stores it in the keychain
 * (overwriting any existing entry), mirrors the public address into
 * settings.json, and returns the new address.
 * 
 * The renderer is responsible for confirming destruction of any
 * existing wallet BEFORE calling this — the Go side just does what it's
 * told to keep the UI flow clean.
 */
export function GenerateWallet(): $CancellablePromise<string> {
    return $Call.ByID(2644982179);
}

/**
 * GetCreditBalance reports the cloud account's remaining credits for the
 * "API key (credit)" payment mode — the same balance the imference web app
 * shows. The renderer passes the key it currently has in the dialog (which may
 * be an unsaved draft); when empty we fall back to the saved key. Returns
 * Configured=false with no error when neither yields a key, so the UI can
 * prompt for one instead of flashing an error.
 */
export function GetCreditBalance(apiKey: string): $CancellablePromise<types$0.CreditInfo> {
    return $Call.ByID(2035079298, apiKey);
}

/**
 * GetEngineInfo reports whether the bundled-engine venv exists and looks
 * runnable. Cheap; safe to call every time the dialog opens.
 */
export function GetEngineInfo(): $CancellablePromise<types$0.EngineInfo> {
    return $Call.ByID(1893224201);
}

/**
 * GetLogs returns the current ring buffer snapshot so the renderer can
 * seed its panel on mount. Subsequent entries arrive via the "log:entry"
 * event.
 */
export function GetLogs(): $CancellablePromise<logbus$0.Entry[] | null> {
    return $Call.ByID(1743981476);
}

/**
 * GetSavedImage reads one gallery file and returns it as a base64 data URL. Goes
 * through the Wails bridge (not an HTTP route) so it works identically in
 * `wails dev`, the packaged build, and on Windows. The renderer calls it lazily
 * per tile (only when scrolled into view), so a large history stays cheap.
 */
export function GetSavedImage(name: string): $CancellablePromise<string> {
    return $Call.ByID(1949400591, name);
}

export function GetSettings(): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(2554697378);
}

export function GetSidecarStatus(): $CancellablePromise<types$0.SidecarStatus> {
    return $Call.ByID(314904788);
}

/**
 * GetVersion returns the app's own version: "dev" for local builds, "X.X.X"
 * for release binaries (embedded by CI, see internal/version).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

/**
 * GetWalletInfo reports the current wallet state to the renderer. Cheap
 * when the keychain has no entry (just an ErrNoWallet round-trip). When
 * configured, also fetches the USDC balance over the Base RPC — that's
 * network I/O, so the call can block for a couple seconds.
 */
export function GetWalletInfo(): $CancellablePromise<types$0.WalletInfo> {
    return $Call.ByID(3063899554);
}

/**
 * ImportWallet parses a hex private key (0x-prefixed or not), stores it
 * in the keychain, mirrors the address to settings, returns the address.
 * Errors on malformed input — caller's textarea should display the message
 * inline so the user knows what to fix.
 */
export function ImportWallet(privateKeyHex: string): $CancellablePromise<string> {
    return $Call.ByID(1678243017, privateKeyHex);
}

/**
 * InstallEngine kicks off the full 5-phase install in a goroutine and returns
 * immediately. Progress is streamed via the "install:progress" Wails event;
 * the renderer listens for {phase:"done"} or {phase:"error"} to know it's
 * finished. Only one install runs at a time — the Installer enforces this.
 */
export function InstallEngine(): $CancellablePromise<void> {
    return $Call.ByID(1246353242);
}

/**
 * ListCloudModels returns the full imference catalog (cloud can run any model
 * code, including the proprietary cloud-only ones the local picker hides).
 * Public endpoint — works without an API key.
 */
export function ListCloudModels(): $CancellablePromise<types$0.ModelInfo[] | null> {
    return $Call.ByID(3132218524);
}

/**
 * ListLocalModels returns the imference catalog filtered to locally-runnable
 * models (those with downloadable weights). Public endpoint — works without an
 * API key, so the picker is usable on first run.
 */
export function ListLocalModels(): $CancellablePromise<types$0.ModelInfo[] | null> {
    return $Call.ByID(4210442862);
}

/**
 * ListSavedImages returns one page of previously-generated images from the
 * output folder, newest first (by file mtime), optionally narrowed by filter.
 * Paginated for infinite scroll: pass the running offset and a page size.
 */
export function ListSavedImages(offset: number, limit: number, filter: types$0.GalleryFilter): $CancellablePromise<types$0.SavedImage[] | null> {
    return $Call.ByID(2064626354, offset, limit, filter);
}

/**
 * LogFromFrontend lets the renderer push captured console.* / window.error
 * events into the same bus, so the LogPanel is a single source of truth.
 * Level is one of "trace" | "info" | "warn" | "error"; unknown → "info".
 */
export function LogFromFrontend(level: string, source: string, message: string, data: any): $CancellablePromise<void> {
    return $Call.ByID(2445038673, level, source, message, data);
}

/**
 * PickModelFile opens the native file picker filtered to .safetensors and
 * returns the chosen absolute path, or "" when the user cancels.
 */
export function PickModelFile(): $CancellablePromise<string> {
    return $Call.ByID(3611692075);
}

/**
 * RefreshWalletBalance bypasses the in-memory balance cache and re-queries
 * the RPC. Bound separately because the renderer's refresh button must
 * always read fresh state, not the 10s-cached one.
 */
export function RefreshWalletBalance(): $CancellablePromise<string> {
    return $Call.ByID(548670143);
}

/**
 * RemoveCustomModel drops a custom checkpoint from the registry (the file on
 * disk is never touched). If it was the active model, the selection is cleared
 * and the engine stopped.
 */
export function RemoveCustomModel(path: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1818023451, path);
}

export function RestartSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2718986071);
}

/**
 * SaveSettings overwrites settings on disk and restarts the sidecar in the
 * background if a sidecar-affecting field changed — but ONLY when the engine is
 * currently running. When it's stopped (the default now — the engine starts on
 * demand), we just persist; the new config applies at the next manual Start.
 * This keeps settings edits (incl. auto-save) from spinning the engine up.
 */
export function SaveSettings(next: types$0.Settings): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1949631069, next);
}

/**
 * SelectCloudModel records which catalog model cloud generation should use.
 * Unlike SelectLocalModel this is instant — no weights to download, no sidecar
 * to restart: it just persists the model code (sent to the server) plus the
 * full catalog entry (so the form can show details and seed generation params).
 */
export function SelectCloudModel(modelCode: string): $CancellablePromise<void> {
    return $Call.ByID(2474969643, modelCode);
}

/**
 * SelectLocalModel downloads the chosen model's weights, deletes the previously
 * downloaded model (only after the new one lands), persists the selection, and
 * restarts the sidecar so the new weights load. Returns immediately; progress
 * streams on the "model:progress" event ({phase:"done"|"error"} terminates).
 */
export function SelectLocalModel(modelCode: string): $CancellablePromise<void> {
    return $Call.ByID(441193013, modelCode);
}

/**
 * StartSidecar boots the local engine on demand (home-screen engine control),
 * loading the currently-selected model. No-op if already starting/ready; errors
 * if the engine isn't installed or no model has been downloaded yet.
 */
export function StartSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2851925842);
}

/**
 * StopSidecar shuts the local engine down to free GPU/RAM.
 */
export function StopSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2431020056);
}

/**
 * UseCustomModel registers a user-supplied checkpoint (referenced in place —
 * never copied, never deleted) and makes it the active local model. The
 * previously downloaded catalog file, if any, is kept on disk so switching
 * back is instant (modelfetch's size-based reuse skips the re-download).
 */
export function UseCustomModel(path: string, backendType: string, baseModel: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(2742322084, path, backendType, baseModel);
}
