// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound facade. Every method on *App becomes a
 * `window.go.main.App.X(...)` Promise-returning function in the frontend,
 * with TypeScript types auto-generated under frontend/wailsjs/.
 * 
 * All persistent state lives in the five substructs (settings, sidecar,
 * cloud, installer, bus). App's job is to wire requests + emit status events;
 * it owns no business logic.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as components$0 from "./internal/components/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logbus$0 from "./internal/logbus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";

/**
 * AddLora registers a LoRA file in the library (referenced in place — never
 * copied, never deleted). Its family is read from the safetensors header so
 * the UI can offer it only with compatible models.
 */
export function AddLora(path: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1589676372, path);
}

/**
 * CancelModelDownload aborts an in-flight local model download (if any). The
 * download goroutine sees context.Canceled, cleans up the partial file, and
 * emits a "cancelled" progress event; a no-op when nothing is downloading.
 */
export function CancelModelDownload(): $CancellablePromise<void> {
    return $Call.ByID(1920008848);
}

/**
 * CheckForUpdate asks GitHub for the latest release and compares it to this
 * build. Local "dev" builds return UpdateAvailable=false without any network
 * call. The frontend treats an error as "no banner" — never blocking startup.
 */
export function CheckForUpdate(): $CancellablePromise<types$0.UpdateInfo> {
    return $Call.ByID(2347956003);
}

/**
 * CheckModelReadiness reports whether a model's shared components — its base
 * repo plus the backend's auxiliary repos (see componentRepos) — are already
 * in the offline tree. STATELESS on purpose: the renderer passes the base
 * repo and backend of the model it is DISPLAYING (which may be a pending
 * pick, not yet the saved LocalModel — reading saved settings here once
 * showed krea2's missing components under a freshly selected SDXL). The UI
 * gates the Generate button on Ready and offers DownloadModelComponents when
 * files are missing — so a cold first generation never hides a download
 * behind "generating". Never gates on uncertainty: a repo without a CDN
 * manifest reports ready and falls back to the engine's lazy download.
 */
export function CheckModelReadiness(baseRepo: string, backend: string): $CancellablePromise<components$0.Readiness> {
    return $Call.ByID(158653036, baseRepo, backend);
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1566804265);
}

/**
 * DeleteCachedModel removes one downloaded checkpoint on the user's request.
 * Refuses the active model — the engine has it mmap'd, so the delete would fail
 * on Windows anyway, and a clear message beats a sharing violation.
 * 
 * key is the only untrusted input reaching the filesystem here: it's validated,
 * then joined, then confined by deleteManagedModel's guard.
 */
export function DeleteCachedModel(key: string): $CancellablePromise<void> {
    return $Call.ByID(3530267161, key);
}

/**
 * DeleteSavedImage removes one file from the output folder. Destructive — the
 * renderer confirms first.
 */
export function DeleteSavedImage(name: string): $CancellablePromise<void> {
    return $Call.ByID(1743119110, name);
}

/**
 * DetectPython runs the same probe the installer will use, but on demand —
 * the SettingsDialog calls this to surface "Python X.Y.Z found at …" before
 * the user even clicks Install.
 */
export function DetectPython(): $CancellablePromise<types$0.PythonInfo> {
    return $Call.ByID(425866076);
}

/**
 * DownloadModelComponents pre-downloads a model's shared components — base
 * repo + backend auxiliaries (see componentRepos) — from the CDN mirror into
 * the engine's offline tree, asynchronously. Stateless like
 * CheckModelReadiness. Progress streams via "components:progress" events; a
 * final "components:done" or "components:error" settles the UI. Idempotent
 * and resumable (present files are skipped; a cancelled run resumes on the
 * next call). On completion each repo's engine completion marker is written,
 * so the cold load is a cache hit. A repo without a CDN manifest is skipped
 * (the engine's lazy path covers it).
 */
export function DownloadModelComponents(baseRepo: string, backend: string): $CancellablePromise<void> {
    return $Call.ByID(2424424962, baseRepo, backend);
}

/**
 * DropPendingCloudJob forgets a persisted cloud job on the user's request — the
 * manual escape hatch for a row wedged on "Running in the cloud…" (a request_id
 * the server will never resolve). It does NOT cancel anything server-side; the
 * result, if one ever lands, stays retrievable by request_id. Any resume already
 * in flight is left to finish harmlessly: it will simply find no record to drop.
 */
export function DropPendingCloudJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2597586911, jobID);
}

/**
 * EnsureLocalModel activates a model whose weights are ALREADY on disk, and
 * reports false without touching anything when they aren't.
 * 
 * This is what the generate path calls: picking a cached model and hitting
 * Generate should just work (the engine restart is the app's problem, not the
 * user's), while starting a multi-GB download stays a deliberate, explicitly
 * clicked act. A miss here means the file was evicted, deleted by hand, or the
 * catalog re-pointed the model at new weights — all cases where the caller must
 * fall back to SelectLocalModel, which downloads.
 */
export function EnsureLocalModel(modelCode: string): $CancellablePromise<boolean> {
    return $Call.ByID(2950114299, modelCode);
}

/**
 * ExportWalletPrivateKey returns the raw hex private key so the user
 * can back it up. The renderer must gate this behind a confirmation
 * modal — once this method returns, the secret is in the renderer's
 * memory (and the user's clipboard if they copy it). NEVER LOGGED here.
 */
export function ExportWalletPrivateKey(): $CancellablePromise<string> {
    return $Call.ByID(2656428036);
}

/**
 * GalleryFacets returns the distinct filterable values across the whole gallery
 * (with counts), for building the filter UI.
 */
export function GalleryFacets(): $CancellablePromise<types$0.GalleryFacets> {
    return $Call.ByID(2527262001);
}

/**
 * GenerateCloud is the only HTTP surface to imference.com. Frontend never
 * touches the network directly — keeps auth-key/wallet handling in Go and
 * gives us a single point to add retries / progress events later.
 * 
 * Dispatches based on settings.PaymentMode:
 *   - "x402"   : signs each request with the local wallet (Base mainnet USDC)
 *   - default  : "bearer" — uses settings.APIKey
 */
export function GenerateCloud(req: types$0.GenerationRequest): $CancellablePromise<types$0.GenerationResult> {
    return $Call.ByID(2634479375, req);
}

/**
 * GenerateLocal dispatches to the running Python sidecar. The sidecar
 * itself is single-threaded (the Engine is stateful) so concurrent calls
 * queue up server-side; that's intentional for the POC.
 */
export function GenerateLocal(req: types$0.GenerationRequest): $CancellablePromise<types$0.GenerationResult> {
    return $Call.ByID(3761455137, req);
}

/**
 * GenerateWallet creates a fresh keypair, stores it in the keychain
 * (overwriting any existing entry), mirrors the public address into
 * settings.json, and returns the new address.
 * 
 * The renderer is responsible for confirming destruction of any
 * existing wallet BEFORE calling this — the Go side just does what it's
 * told to keep the UI flow clean.
 */
export function GenerateWallet(): $CancellablePromise<string> {
    return $Call.ByID(2644982179);
}

/**
 * GetCreditBalance reports the cloud account's remaining credits for the
 * "API key (credit)" payment mode — the same balance the imference web app
 * shows. The renderer passes the key it currently has in the dialog (which may
 * be an unsaved draft); when empty we fall back to the saved key. Returns
 * Configured=false with no error when neither yields a key, so the UI can
 * prompt for one instead of flashing an error.
 */
export function GetCreditBalance(apiKey: string): $CancellablePromise<types$0.CreditInfo> {
    return $Call.ByID(2035079298, apiKey);
}

/**
 * GetEngineInfo reports whether the bundled-engine venv exists and looks
 * runnable. Cheap; safe to call every time the dialog opens.
 */
export function GetEngineInfo(): $CancellablePromise<types$0.EngineInfo> {
    return $Call.ByID(1893224201);
}

/**
 * GetFolderSizes walks the three cache trees. SLOW — the engine venv alone is
 * tens of thousands of files — so it's deliberately separate from
 * GetStorageInfo and the UI resolves it after painting.
 */
export function GetFolderSizes(): $CancellablePromise<types$0.FolderSizes> {
    return $Call.ByID(55724427);
}

/**
 * GetLogs returns the current ring buffer snapshot so the renderer can
 * seed its panel on mount. Subsequent entries arrive via the "log:entry"
 * event.
 */
export function GetLogs(): $CancellablePromise<logbus$0.Entry[] | null> {
    return $Call.ByID(1743981476);
}

/**
 * GetSavedImage reads one gallery file and returns it as a base64 data URL. Goes
 * through the Wails bridge (not an HTTP route) so it works identically in
 * `wails dev`, the packaged build, and on Windows. The renderer calls it lazily
 * per tile (only when scrolled into view), so a large history stays cheap.
 */
export function GetSavedImage(name: string): $CancellablePromise<string> {
    return $Call.ByID(1949400591, name);
}

export function GetSettings(): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(2554697378);
}

export function GetSidecarStatus(): $CancellablePromise<types$0.SidecarStatus> {
    return $Call.ByID(314904788);
}

/**
 * GetStorageInfo is the cheap storage readout: index totals plus one syscall.
 */
export function GetStorageInfo(): $CancellablePromise<types$0.StorageInfo> {
    return $Call.ByID(3330596760);
}

/**
 * GetVersion returns the app's own version: "dev" for local builds, "X.X.X"
 * for release binaries (embedded by CI, see internal/version).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

/**
 * GetWalletInfo reports the current wallet state to the renderer. Cheap
 * when the keychain has no entry (just an ErrNoWallet round-trip). When
 * configured, also fetches the USDC balance over the Base RPC — that's
 * network I/O, so the call can block for a couple seconds.
 */
export function GetWalletInfo(): $CancellablePromise<types$0.WalletInfo> {
    return $Call.ByID(3063899554);
}

/**
 * ImportWallet parses a hex private key (0x-prefixed or not), stores it
 * in the keychain, mirrors the address to settings, returns the address.
 * Errors on malformed input — caller's textarea should display the message
 * inline so the user knows what to fix.
 */
export function ImportWallet(privateKeyHex: string): $CancellablePromise<string> {
    return $Call.ByID(1678243017, privateKeyHex);
}

/**
 * InstallEngine kicks off the full 5-phase install in a goroutine and returns
 * immediately. Progress is streamed via the "install:progress" Wails event;
 * the renderer listens for {phase:"done"} or {phase:"error"} to know it's
 * finished. Only one install runs at a time — the Installer enforces this.
 */
export function InstallEngine(): $CancellablePromise<void> {
    return $Call.ByID(1246353242);
}

/**
 * ListCachedModels returns the downloaded checkpoints, most recently used
 * first. Served straight from the index — no disk walk, safe to call on every
 * picker open.
 */
export function ListCachedModels(): $CancellablePromise<types$0.CachedModel[] | null> {
    return $Call.ByID(200825589);
}

/**
 * ListCloudModels returns the full imference catalog (cloud can run any model
 * code, including the proprietary cloud-only ones the local picker hides).
 * Public endpoint — works without an API key.
 */
export function ListCloudModels(): $CancellablePromise<types$0.ModelInfo[] | null> {
    return $Call.ByID(3132218524);
}

/**
 * ListLocalModels returns the imference catalog filtered to locally-runnable
 * models (those with downloadable weights). Public endpoint — works without an
 * API key, so the picker is usable on first run.
 */
export function ListLocalModels(): $CancellablePromise<types$0.ModelInfo[] | null> {
    return $Call.ByID(4210442862);
}

/**
 * ListPendingCloudJobs returns the cloud generations persisted as in-flight, so
 * the renderer can rehydrate the Activity list on launch. Excludes any currently
 * owned by a live call/resume (those settle through their own path).
 */
export function ListPendingCloudJobs(): $CancellablePromise<types$0.PendingCloudJob[] | null> {
    return $Call.ByID(3538303025);
}

/**
 * ListSavedImages returns one page of previously-generated images from the
 * output folder, newest first (by file mtime), optionally narrowed by filter.
 * Paginated for infinite scroll: pass the running offset and a page size.
 */
export function ListSavedImages(offset: number, limit: number, filter: types$0.GalleryFilter): $CancellablePromise<types$0.SavedImage[] | null> {
    return $Call.ByID(2064626354, offset, limit, filter);
}

/**
 * LogFromFrontend lets the renderer push captured console.* / window.error
 * events into the same bus, so the LogPanel is a single source of truth.
 * Level is one of "trace" | "info" | "warn" | "error"; unknown → "info".
 */
export function LogFromFrontend(level: string, source: string, message: string, data: any): $CancellablePromise<void> {
    return $Call.ByID(2445038673, level, source, message, data);
}

/**
 * OpenCacheFolder reveals one of the three known cache directories in the OS
 * file manager. kind is an allow-list, never a path — the frontend can't ask
 * for an arbitrary location.
 */
export function OpenCacheFolder(kind: string): $CancellablePromise<void> {
    return $Call.ByID(1027032673, kind);
}

/**
 * PickLoraFile opens the native file picker filtered to .safetensors and
 * returns the chosen absolute path, or "" when the user cancels.
 */
export function PickLoraFile(): $CancellablePromise<string> {
    return $Call.ByID(2628065406);
}

/**
 * PickModelFile opens the native file picker filtered to .safetensors and
 * returns the chosen absolute path, or "" when the user cancels.
 */
export function PickModelFile(): $CancellablePromise<string> {
    return $Call.ByID(3611692075);
}

/**
 * PurgeBaseComponentsCache empties model-cache/, the shared text-encoder/VAE
 * tree the Python engine fills from the CDN. Outside the LRU quota on purpose:
 * those files are shared by every checkpoint of a family, so evicting them
 * automatically would re-download 8–10 GB the next time any of them loads.
 * 
 * The engine is stopped first: on Windows RemoveAll over open files fails
 * halfway and leaves a half-destroyed tree, which is worse than refusing.
 */
export function PurgeBaseComponentsCache(): $CancellablePromise<void> {
    return $Call.ByID(3351197237);
}

/**
 * RecheckPendingCloud re-polls every persisted pending job that isn't already
 * being handled. Fired by the Activity "Recheck" action; also runs once at
 * startup. Each resumed job settles via the "cloud:resolved" event.
 */
export function RecheckPendingCloud(): $CancellablePromise<void> {
    return $Call.ByID(2444376496);
}

/**
 * RefreshWalletBalance bypasses the in-memory balance cache and re-queries
 * the RPC. Bound separately because the renderer's refresh button must
 * always read fresh state, not the 10s-cached one.
 */
export function RefreshWalletBalance(): $CancellablePromise<string> {
    return $Call.ByID(548670143);
}

/**
 * RemoveCustomModel drops a custom checkpoint from the registry (the file on
 * disk is never touched). If it was the active model, the selection is cleared
 * and the engine stopped.
 */
export function RemoveCustomModel(path: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1818023451, path);
}

/**
 * RemoveLora drops a LoRA from the library. The file itself is left on disk.
 */
export function RemoveLora(path: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1195692449, path);
}

export function RestartSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2718986071);
}

/**
 * RevealInFolder opens the OS file manager with the given file highlighted
 * (Finder / Explorer / the default Linux file manager). The path is confined to
 * the output directory so the renderer can't ask us to reveal arbitrary files.
 */
export function RevealInFolder(imgPath: string): $CancellablePromise<void> {
    return $Call.ByID(1947324723, imgPath);
}

/**
 * SaveSettings overwrites settings on disk and restarts the sidecar in the
 * background if a sidecar-affecting field changed — but ONLY when the engine is
 * currently running. When it's stopped (the default now — the engine starts on
 * demand), we just persist; the new config applies at the next manual Start.
 * This keeps settings edits (incl. auto-save) from spinning the engine up.
 */
export function SaveSettings(next: types$0.Settings): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(1949631069, next);
}

/**
 * SelectCloudModel records which catalog model cloud generation should use.
 * Unlike SelectLocalModel this is instant — no weights to download, no sidecar
 * to restart: it just persists the model code (sent to the server) plus the
 * full catalog entry (so the form can show details and seed generation params).
 */
export function SelectCloudModel(modelCode: string): $CancellablePromise<void> {
    return $Call.ByID(2474969643, modelCode);
}

/**
 * SelectLocalModel makes the chosen model active, downloading its weights only
 * when they aren't already cached, then restarts the sidecar so they load.
 * Returns immediately; progress streams on the "model:progress" event
 * ({phase:"done"|"error"} terminates).
 * 
 * Previously downloaded models are KEPT (up to the cache quota), so coming back
 * to one is a restart rather than a multi-GB re-download. Making room, when
 * needed, evicts least-recently-used models — never the active one.
 */
export function SelectLocalModel(modelCode: string): $CancellablePromise<void> {
    return $Call.ByID(441193013, modelCode);
}

/**
 * StartSidecar boots the local engine on demand (home-screen engine control),
 * loading the currently-selected model. No-op if already starting/ready; errors
 * if the engine isn't installed or no model has been downloaded yet.
 */
export function StartSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2851925842);
}

/**
 * StopLocalGeneration aborts the in-flight local generation. runqy_python's task
 * loop is single-threaded — while a denoise runs it isn't reading stdin, so the
 * running image can't be cancelled cooperatively. We hard-kill the sidecar
 * (which aborts the current generate) and reload the model so the engine is
 * ready for the next queued job. Returns immediately; the restart runs in the
 * background and the killed request's Generate call fails, which the renderer
 * maps to a "stopped" job. No-op when nothing is generating.
 */
export function StopLocalGeneration(): $CancellablePromise<void> {
    return $Call.ByID(1928099974);
}

/**
 * StopSidecar shuts the local engine down to free GPU/RAM.
 */
export function StopSidecar(): $CancellablePromise<void> {
    return $Call.ByID(2431020056);
}

/**
 * UseCustomModel registers a user-supplied checkpoint (referenced in place —
 * never copied, never deleted) and makes it the active local model. The
 * previously downloaded catalog file, if any, is kept on disk so switching
 * back is instant (modelfetch's size-based reuse skips the re-download).
 */
export function UseCustomModel(path: string, backendType: string, baseModel: string): $CancellablePromise<types$0.Settings> {
    return $Call.ByID(2742322084, path, backendType, baseModel);
}
