// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CachedModel is one downloaded checkpoint, as shown in Settings → Storage.
 * Key is its filename in the managed models dir — the handle for deletion.
 */
export interface CachedModel {
    "key": string;
    "modelCode"?: string;
    "modelName"?: string;
    "bytes": number;
    "lastUsedAt": string;

    /**
     * Active marks the model the engine currently has loaded — it can't be
     * deleted (the file is mmap'd) and is never evicted.
     */
    "active": boolean;

    /**
     * Orphan marks a file whose provenance is unknown (a leftover from an older
     * build, or indexed while the catalog was unreachable). Evicted first.
     */
    "orphan": boolean;
}

/**
 * CreditInfo is the renderer's view of the cloud account's remaining credits,
 * fetched with the Bearer API key (the "API key (credit)" payment mode). Mirrors
 * the balance readout the imference web app shows. Configured is false when no
 * key is set, so the Settings UI can prompt for a key instead of showing an error.
 */
export interface CreditInfo {
    /**
     * true when an API key was available to query
     */
    "configured": boolean;

    /**
     * remaining credit balance
     */
    "credits": number;

    /**
     * populated on a failed lookup (bad key, network)
     */
    "error"?: string;
}

/**
 * EngineInfo reflects whether the bundled-engine venv exists and looks valid.
 * Computed on demand by GetEngineInfo — cheap, fast, can be called every time
 * the SettingsDialog opens.
 */
export interface EngineInfo {
    "installed": boolean;
    "venvDir": string;
    "pythonPath": string;

    /**
     * EngineVersion is the imference-engine version currently installed in the
     * venv (via importlib.metadata), "" when unknown / not installed.
     */
    "engineVersion": string;

    /**
     * PinnedVersion is the version the desktop ships with (parsed from
     * EngineTarball), "" under a dev source override where no version is enforced.
     */
    "pinnedVersion": string;

    /**
     * Outdated is true when both versions are known and differ — the startup
     * check force-reinstalls the pinned engine in that case. Always false for a
     * Dev (editable) install, which is pinned to its working tree, not a release.
     */
    "outdated": boolean;

    /**
     * Dev is true when the engine is an editable (`pip install -e`) checkout —
     * a local dev source, not an official release. Detected from PEP 610
     * direct_url.json in the venv.
     */
    "dev": boolean;

    /**
     * DevPath is the editable checkout's source directory when Dev is true ("" otherwise).
     */
    "devPath": string;
}

/**
 * EngineRuntimeSettings holds host-tuning for the engine. All seven image
 * backends (SDXL, SD 1.5, Z-Image, FLUX, Chroma, Qwen-Image, Anima) share the
 * engine's single IMAGE_* env contract and only one loads per sidecar, so they
 * share ONE Image block rather than a block each. WAN video has its own WAN_*
 * contract. (Pre-unification builds stored separate `sdxl`/`zimage` blocks;
 * settings.reload() migrates the old `sdxl` block into `image`.)
 */
export interface EngineRuntimeSettings {
    "image": ImageRuntimeSettings;
    "wan": WanRuntimeSettings;
}

/**
 * Facet is one filterable value with how many saved images carry it.
 */
export interface Facet {
    "value": string;
    "label": string;
    "count": number;
}

/**
 * FolderSizes is the expensive part of the storage readout — each figure is a
 * full directory walk (the engine venv holds tens of thousands of files), so
 * it's a separate call the UI resolves after painting.
 */
export interface FolderSizes {
    "modelsBytes": number;
    "baseCacheBytes": number;
    "engineBytes": number;
}

/**
 * FormatOption is one supported resolution/ratio for a model (from im_format).
 */
export interface FormatOption {
    "formatCode": string;
    "name"?: string;
    "width": number;
    "height": number;
    "ratio"?: string;
    "isDefault": boolean;

    /**
     * CreditMultiplier scales the model's per-run price for this format (1 = SD,
     * 2 = HD). nil = no surcharge. The composer shows the resulting price, so it
     * applies the same formula the server bills with.
     */
    "creditMultiplier"?: number | null;
}

/**
 * GalleryFacets are the distinct filterable values across the whole gallery,
 * used to build the filter UI.
 */
export interface GalleryFacets {
    "models": Facet[] | null;
    "engines": Facet[] | null;
    "sources": Facet[] | null;
}

/**
 * GalleryFilter narrows ListSavedImages. Empty fields mean "no constraint".
 */
export interface GalleryFilter {
    /**
     * e.g. "sdxl" | "flux" | "zimage" | "wan"
     */
    "engine": string;

    /**
     * exact catalog code
     */
    "modelCode": string;

    /**
     * "local" | "cloud"
     */
    "source": string;

    /**
     * free-text, matched against the prompt (case-insensitive)
     */
    "text": string;
}

export interface GenerationMeta {
    "prompt": string;
    "negativePrompt"?: string;

    /**
     * "local" | "cloud"
     */
    "source": string;

    /**
     * catalog code
     */
    "modelCode"?: string;

    /**
     * display name
     */
    "modelName"?: string;

    /**
     * e.g. "sdxl" | "flux" | "zimage" | "wan"
     */
    "engine"?: string;
    "width"?: number;
    "height"?: number;

    /**
     * "square" | "portrait" | "landscape"
     */
    "formatCode"?: string;
    "numSteps"?: number;
    "guidanceScale"?: number;
    "scheduler"?: string;
    "clipSkip"?: number | null;
    "seed": number;
    "img2img"?: boolean;
    "strength"?: number;
    "loras"?: LoraRef[] | null;

    /**
     * RFC3339
     */
    "createdAt": string;
}

/**
 * GenerationRequest is the unified frontend → Go payload for both modes.
 * Mirrors imference-desktop/src/renderer/src/lib/types.ts GenerationParams.
 */
export interface GenerationRequest {
    "prompt": string;
    "negativePrompt"?: string;
    "width": number;
    "height": number;
    "numSteps": number;
    "guidanceScale": number;

    /**
     * Seed is a pointer so the JSON can carry null (= random) vs 0 (= explicit zero).
     */
    "seed"?: number | null;

    /**
     * Scheduler and ClipSkip are usually injected server-side from the selected
     * LocalModel's config (App.GenerateLocal) rather than set by the renderer,
     * but the fields exist so a caller can override. Empty/nil → engine default.
     */
    "scheduler"?: string;
    "clipSkip"?: number | null;

    /**
     * RefImages are the model's reference images, in slot order — slot 0 is the
     * img2img source (or a video's first frame), slot 1 a video's last frame.
     * Always optional: a model that accepts them still runs prompt-only. How
     * many slots a model offers comes from ModelInfo.RefImages.
     * 
     * SourceImage below stays the wire field for slot 0 so the engine contract
     * (and every shipped sidecar) is untouched; normalizeRefImages keeps the two
     * in sync, whichever one the caller filled.
     */
    "refImages"?: string[] | null;

    /**
     * SourceImage enables img2img: a base64 source the engine denoises from
     * instead of pure noise. May be a data-URL ("data:image/png;base64,…") or
     * raw base64 — the sidecar client strips any data-URL prefix. Empty = text2img.
     */
    "sourceImage"?: string;

    /**
     * Strength is the img2img denoising strength (0 = keep source, 1 = ignore it).
     * FormatCode is the format the user selected; the cloud price depends on it.
     */
    "formatCode"?: string;

    /**
     * DurationS is the requested clip length in seconds — cloud video models
     * that publish duration bounds. Ignored by the local sidecar, whose
     * generate() takes no such kwarg.
     */
    "durationS"?: number;

    /**
     * Only meaningful with SourceImage set. 0/unset → engine default (0.75). In
     * img2img the output size is derived from the source image (Width/Height ignored).
     */
    "strength"?: number;

    /**
     * Loras are stacked on the local model (local mode, SDXL only for now —
     * see loras.BackendSupports). Paths must be entries of Settings.Loras.
     */
    "loras"?: LoraRef[] | null;
}

/**
 * GenerationResult is the unified Go → frontend response. Same shape for
 * cloud and local: image always arrives as base64 PNG/WebP so the React
 * side just sets `<img src="data:image/png;base64,..."/>` regardless of source.
 */
export interface GenerationResult {
    "imageBase64": string;
    "seed": number;

    /**
     * "cloud" | "local"
     */
    "source": string;

    /**
     * SavedPath is the absolute path to the auto-saved copy on disk. Empty
     * string when save failed (the failure is logged but doesn't fail the
     * generation — the in-memory base64 result is still usable).
     */
    "savedPath": string;

    /**
     * Meta is the generation metadata (same as the sidecar), so the freshly
     * generated image shows the same details in the UI as gallery images.
     */
    "meta"?: GenerationMeta | null;
}

/**
 * ImageRuntimeSettings tunes the active image backend (shared IMAGE_* env
 * contract). UseTinyVAE only affects SDXL / SD 1.5; the engine ignores it for
 * Z-Image / FLUX / Chroma / Qwen-Image / Anima.
 */
export interface ImageRuntimeSettings {
    /**
     * Device: "" / "auto" | cuda | cuda:N | mps | cpu. "cuda" covers BOTH
     * NVIDIA and AMD GPUs — torch's ROCm build presents the AMD GPU under the
     * cuda device string, so there is no separate "rocm" value.
     */
    "device"?: string;

    /**
     * SDXL/SD1.5 TAESD — ~10× faster VAE decode
     */
    "useTinyVae"?: boolean;

    /**
     * EnableCPUOffload is tri-state: nil = Auto (the desktop enables offload on
     * NVIDIA/AMD cards below autoOffloadVRAMThresholdGiB — see resolveCPUOffload
     * — so a small-VRAM GPU doesn't oversubscribe VRAM and crawl via WDDM
     * shared-memory spill), *true = force on, *false = force off. On a card the
     * full pipe fits on, Auto leaves it off (full residency is fastest).
     */
    "enableCpuOffload"?: boolean | null;

    /**
     * OffloadMode picks the offload MECHANISM when offload is enabled
     * (engine env IMAGE_OFFLOAD_MODE): "" or "auto" = backend+VRAM-aware pick
     * (heavy DiTs whose compute module can't fit the card get "group" —
     * block-streamed, ~5-6 GB peak VRAM; everything else gets "model"),
     * "model" / "group" force it. Ignored while offload is off.
     */
    "offloadMode"?: string;

    /**
     * "" / "auto" / int
     */
    "maxGpuModels"?: string;

    /**
     * "" / "auto" / int
     */
    "maxCpuModels"?: string;
}

/**
 * LoraEntry is one LoRA file in the user's library.
 */
export interface LoraEntry {
    "path": string;
    "name": string;

    /**
     * Family is the model family the file was trained for ("sdxl", "sd15",
     * "flux", …), read from its safetensors header; "" when unrecognized.
     */
    "family"?: string;
    "sizeBytes": number;

    /**
     * TriggerWords are the prompt words the file says it was trained with.
     */
    "triggerWords"?: string[] | null;

    /**
     * TextEncoderTrained false = UNet-only LoRA: trigger words are optional.
     */
    "textEncoderTrained"?: boolean;
}

/**
 * LoraRef is one LoRA applied to a generation.
 */
export interface LoraRef {
    "path": string;
    "name"?: string;
    "weight": number;
}

/**
 * ModelInfo is one entry from imference.com/api/models, trimmed to the fields
 * the desktop app uses. Doubles as the JSON contract for the frontend model
 * picker. Only models with a non-empty ModelURL can run locally — the rest are
 * cloud-only / proprietary (Flux, GPT-Image, Veo, Wan video, …).
 */
export interface ModelInfo {
    "modelCode": string;
    "name": string;
    "shortDescription": string;
    "mediumDescription": string;

    /**
     * thumbnail URL
     */
    "image": string;

    /**
     * downloadable .safetensors ("" = cloud-only)
     */
    "modelUrl": string;

    /**
     * LocalPath is the absolute path of a user-supplied checkpoint (custom
     * model added via UseCustomModel). Non-empty = custom: no catalog entry,
     * no download — the sidecar loads this file directly.
     */
    "localPath"?: string;
    "promptPre": string;
    "promptNegative": string;

    /**
     * Steps / cfg / clip-skip bounds, straight from the catalog. A nil Default
     * is the catalog saying the model has no such knob — the form then offers no
     * control for it, rather than a slider that moves nothing (gpt-image-1
     * publishes neither steps nor cfg; minimax-h3 no cfg). Same contract as the
     * Duration trio below.
     */
    "stepsDefault"?: number | null;
    "stepsMin"?: number | null;
    "stepsMax"?: number | null;
    "cfgDefault"?: number | null;
    "cfgMin"?: number | null;
    "cfgMax"?: number | null;

    /**
     * clip-skip
     */
    "skipDefault"?: number | null;
    "schedulerDefault": string;
    "formatCode": string;

    /**
     * BackendType is the internal engine backend, normalized from the catalog's
     * im_engine field, one of the image backends (sdxl, sd15, zimage, flux,
     * chroma, qwenimage, anima) or "wan". (im_engine "external" and null
     * are filtered out upstream in cloud.ListModels — not locally runnable.)
     */
    "backendType"?: string;

    /**
     * BaseModel is the HF repo id of the shared base-components a backend needs
     * (Z-Image finetunes, e.g. "Tongyi-MAI/Z-Image-Turbo"). Empty for
     * self-contained SDXL single-file checkpoints. Resolved offline via the CDN.
     */
    "baseModel"?: string;

    /**
     * ShiftDefault is the Z-Image flow-matching shift (3.0≈480p, 5.0≈720p),
     * passed as backend_options={"shift": …}. Ignored by SDXL. 0 → engine default.
     */
    "shiftDefault"?: number;

    /**
     * Cost is the cloud run cost in credits (1 credit = $0.001). Local runs are
     * free. CanLocal/CanCloud declare where the model may run.
     */
    "cost": number;
    "canLocal": boolean;
    "canCloud": boolean;

    /**
     * RefImages is how many reference images the model takes, resolved from the
     * catalog's accepts_image_input + image_input_max: 0 = none, 1 = a single
     * source image (img2img), 2 = first + last frame (video interpolation).
     * Reference images are always OPTIONAL — a model that accepts them still
     * runs from the prompt alone.
     * 
     * Resolved in cloud.refImageSlots: a catalog row that omits the capability
     * falls back to 1 for locally-runnable models, preserving the img2img
     * affordance every local model had before the columns existed.
     */
    "refImages": number;

    /**
     * HasAudio marks a video model whose output carries an audio track
     * (catalog has_audio). Carried through for the UI to surface; nothing in the
     * generation path depends on it.
     */
    "hasAudio"?: boolean;

    /**
     * ModelType is what the model produces: "image" or "video". Resolved on the
     * Go side (catalog model_type, else the engine) so the UI never guesses.
     */
    "modelType"?: string;

    /**
     * Duration controls (seconds) for video models that let the caller pick a
     * clip length. A nil Default means the model has no such control — the
     * composer then offers nothing, rather than a slider that changes nothing.
     */
    "durationDefault"?: number | null;
    "durationMin"?: number | null;
    "durationMax"?: number | null;

    /**
     * Formats are the model's supported resolutions/ratios (im_format). Empty
     * when the catalog has none — the UI then falls back to generic formats.
     */
    "formats"?: FormatOption[] | null;

    /**
     * Catalog organization (im_model family/group) for sorting/grouping the list.
     */
    "order"?: number;
    "familyCode"?: string;
    "familyName"?: string;

    /**
     * FamilyOrder is the catalog's display rank for the family. The picker uses
     * it to order the groups it builds from families — cloud-only models with no
     * local backend to group by.
     */
    "familyOrder"?: number;
    "groupCode"?: string;
}

/**
 * GenerationMeta captures how an image was produced. Written verbatim to a
 * "<image>.json" sidecar at save time, and read back to drive the gallery's
 * detail view and filters. Format-agnostic — reused as-is for future video.
 * PendingCloudJob is one in-flight cloud generation persisted to disk so it
 * survives an app close / crash / poll timeout. Recorded at enqueue (once the
 * server returns a request_id), removed on completion. On next launch the app
 * resumes polling each one — the request_id + result live server-side forever,
 * so a paid-for generation is never lost. Rail is "credits" | "x402".
 */
export interface PendingCloudJob {
    "jobId": string;
    "requestId": string;

    /**
     * image | video
     */
    "kind": string;
    "rail": string;
    "prompt": string;
    "meta"?: GenerationMeta | null;
    "createdAt": string;
}

/**
 * PythonInfo is the result of DetectPython: which interpreter we picked, and
 * its self-reported version. Used by the frontend's installer panel.
 */
export interface PythonInfo {
    "path": string;
    "version": string;
}

/**
 * SavedImage is one previously-generated image found on disk in the output
 * folder. The renderer fetches its bytes lazily via GetSavedImage(name) (base64
 * over the Wails bridge). Basic fields are parsed from the filename
 * "<YYYYMMDD-HHMMSS>_<source>_<seed>.<ext>"; Meta comes from the "<name>.json"
 * sidecar when present.
 */
export interface SavedImage {
    /**
     * file name (key for GetSavedImage / DeleteSavedImage)
     */
    "name": string;

    /**
     * Kind is the media kind by extension: "image" | "video". Drives <img> vs
     * <video> rendering in the gallery/lightbox.
     */
    "kind": string;

    /**
     * "local" | "cloud" | …
     */
    "source": string;

    /**
     * 0 when unparseable
     */
    "seed": number;

    /**
     * absolute path on disk
     */
    "savedPath": string;

    /**
     * Width/Height let the renderer reserve the right aspect box before the bytes
     * load (masonry with any format). 0 when the header couldn't be read.
     */
    "width": number;
    "height": number;

    /**
     * Meta is the generation metadata from the sidecar JSON. Nil for images saved
     * before this feature (or hand-added files).
     */
    "meta"?: GenerationMeta | null;
}

/**
 * Settings persisted via internal/settings.Store. Empty strings are the
 * signal for "not configured" — the frontend offers the SettingsDialog when
 * any required field is empty.
 */
export interface Settings {
    "apiKey": string;
    "pythonPath": string;
    "sdxlPath": string;
    "cloudModel": string;

    /**
     * OutputDir overrides where generated images are auto-saved. When empty,
     * defaults to imagesink.DefaultDir() (typically <home>/Pictures/Imference).
     */
    "outputDir": string;

    /**
     * PaymentMode picks the cloud auth scheme: "bearer" (default; uses APIKey)
     * or "x402" (pays per request from the local wallet on Base mainnet).
     */
    "paymentMode": string;

    /**
     * WalletAddress is the public EVM address of the configured wallet,
     * mirrored here for display in the UI when the renderer hasn't unlocked
     * the keychain yet. The private key itself NEVER lives in this file —
     * it's in the OS keychain (Windows Credential Manager).
     */
    "walletAddress": string;

    /**
     * LocalModel is the currently-selected local model (chosen from the
     * imference catalog and downloaded to SDXLPath). Nil until the user picks
     * one. Its config drives local generation defaults — see App.GenerateLocal.
     */
    "localModel"?: ModelInfo | null;

    /**
     * EngineRuntime holds host-machine tuning for the engine (device, VAE mode,
     * offload, model-residency caps, WAN quantization). Applied as env vars when
     * the sidecar starts. NOT generation params — those live in the generation UI.
     */
    "engineRuntime": EngineRuntimeSettings;

    /**
     * CloudModelInfo is the full catalog entry for the selected cloud model
     * (CloudModel holds just its code, the value actually sent to the server).
     * Stored so the form selector can show the model's details and seed cloud
     * generation params (steps/cfg/resolution) the same way LocalModel does.
     * Nil until the user picks a cloud model from the form.
     */
    "cloudModelInfo"?: ModelInfo | null;

    /**
     * CustomModels are user-supplied checkpoints (LocalPath set) registered via
     * UseCustomModel, kept so they stay selectable in the model dropdown. The
     * files themselves are referenced in place — never copied, never deleted.
     * UI-only: not a sidecar-affecting field (the active model is LocalModel).
     */
    "customModels"?: ModelInfo[] | null;

    /**
     * Loras is the user's LoRA library, registered via AddLora. Files are
     * referenced in place — never copied, never deleted.
     */
    "loras"?: LoraEntry[] | null;

    /**
     * ModelCacheQuotaBytes caps the total size of downloaded weights. Downloaded
     * models are kept so switching back is instant; past the quota the least
     * recently used are evicted. 0 means the default (modelcache.DefaultQuotaBytes).
     * The ACTIVE model is never evicted, so the total can exceed this transiently.
     * Excludes the shared base-component cache (model-cache/), which is purged
     * manually — those files are shared across every checkpoint of a family.
     */
    "modelCacheQuotaBytes"?: number;

    /**
     * ModelCacheMinFreeBytes is the free-space cushion to preserve on the cache
     * volume. Unlike the quota (a housekeeping target), this is a hard wall: a
     * download that would eat into it fails before any network call. 0 = default.
     */
    "modelCacheMinFreeBytes"?: number;
}

/**
 * SidecarStatus is broadcast via Wails events on the "sidecar:status" channel
 * every time the sidecar manager transitions states. The frontend uses the
 * `state` discriminator to render the header pill and to enable/disable the
 * Run Local button.
 */
export interface SidecarStatus {
    /**
     * idle | starting | ready | error | stopped
     */
    "state": string;
    "port"?: number;
    "device"?: string;
    "message"?: string;
}

/**
 * StorageInfo is the cheap storage readout: everything here comes from the
 * cache index plus one syscall, so it's safe to fetch on dialog open.
 */
export interface StorageInfo {
    "quotaBytes": number;
    "minFreeBytes": number;
    "usedBytes": number;
    "freeBytes": number;
    "modelsDir": string;
    "baseCacheDir": string;
    "engineDir": string;
}

/**
 * UpdateInfo is the result of App.CheckForUpdate: the app's own version vs the
 * latest GitHub release. URL is the release page to open in the browser —
 * there is no in-app download (the app isn't code-signed yet).
 */
export interface UpdateInfo {
    /**
     * "dev" or "X.X.X"
     */
    "currentVersion": string;

    /**
     * "X.X.X" (tag without v)
     */
    "latestVersion"?: string;

    /**
     * release page html_url
     */
    "url"?: string;
    "updateAvailable": boolean;
}

/**
 * WalletInfo is what the renderer sees when it asks about the wallet
 * status. The private key is never exposed through this struct.
 */
export interface WalletInfo {
    /**
     * true if a key exists in the keychain
     */
    "configured": boolean;

    /**
     * checksummed hex (0x…) or ""
     */
    "address": string;

    /**
     * human string ("1.234"), atomic / 10^6
     */
    "balanceUSDC": string;

    /**
     * always "base-mainnet" in this POC
     */
    "network": string;
    "error"?: string;
}

/**
 * WanRuntimeSettings tunes the WAN video backend (WAN_* env contract). Applies
 * once the video backend is enabled; ignored by the image backends. The two
 * bool knobs are pointers because the engine defaults them to true — nil means
 * "leave at engine default", *false means the user explicitly disabled it.
 */
export interface WanRuntimeSettings {
    "device"?: string;

    /**
     * "" / "auto" | gguf_q8 | gguf_q6 | gguf_q5 | gguf_q4
     */
    "memoryProfile"?: string;

    /**
     * "" / int8 | none
     */
    "textEncoderQuant"?: string;

    /**
     * engine default true
     */
    "vaeTiling"?: boolean | null;

    /**
     * engine default true
     */
    "enableOffload"?: boolean | null;

    /**
     * "" / int
     */
    "maxResident"?: string;
}
