// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreditInfo is the renderer's view of the cloud account's remaining credits,
 * fetched with the Bearer API key (the "API key (credit)" payment mode). Mirrors
 * the balance readout the imference web app shows. Configured is false when no
 * key is set, so the Settings UI can prompt for a key instead of showing an error.
 */
export interface CreditInfo {
    /**
     * true when an API key was available to query
     */
    "configured": boolean;

    /**
     * remaining credit balance
     */
    "credits": number;

    /**
     * populated on a failed lookup (bad key, network)
     */
    "error"?: string;
}

/**
 * EngineInfo reflects whether the bundled-engine venv exists and looks valid.
 * Computed on demand by GetEngineInfo — cheap, fast, can be called every time
 * the SettingsDialog opens.
 */
export interface EngineInfo {
    "installed": boolean;
    "venvDir": string;
    "pythonPath": string;
}

/**
 * EngineRuntimeSettings holds per-backend host-tuning. SDXL and Z-Image each get
 * their own block even though they share the engine's IMAGE_* env contract: only
 * one image backend is loaded per sidecar (chosen by the model's im_engine), so
 * the manager emits IMAGE_* from the block matching the active backend.
 */
export interface EngineRuntimeSettings {
    "sdxl": ImageRuntimeSettings;
    "zimage": ZImageRuntimeSettings;
    "wan": WanRuntimeSettings;
}

/**
 * Facet is one filterable value with how many saved images carry it.
 */
export interface Facet {
    "value": string;
    "label": string;
    "count": number;
}

/**
 * FormatOption is one supported resolution/ratio for a model (from im_format).
 */
export interface FormatOption {
    "formatCode": string;
    "name"?: string;
    "width": number;
    "height": number;
    "ratio"?: string;
    "isDefault": boolean;
}

/**
 * GalleryFacets are the distinct filterable values across the whole gallery,
 * used to build the filter UI.
 */
export interface GalleryFacets {
    "models": Facet[] | null;
    "engines": Facet[] | null;
    "sources": Facet[] | null;
}

/**
 * GalleryFilter narrows ListSavedImages. Empty fields mean "no constraint".
 */
export interface GalleryFilter {
    /**
     * "sdxl" | "zimage" | "wan"
     */
    "engine": string;

    /**
     * exact catalog code
     */
    "modelCode": string;

    /**
     * "local" | "cloud"
     */
    "source": string;
}

/**
 * GenerationMeta captures how an image was produced. Written verbatim to a
 * "<image>.json" sidecar at save time, and read back to drive the gallery's
 * detail view and filters. Format-agnostic — reused as-is for future video.
 */
export interface GenerationMeta {
    "prompt": string;
    "negativePrompt"?: string;

    /**
     * "local" | "cloud"
     */
    "source": string;

    /**
     * catalog code
     */
    "modelCode"?: string;

    /**
     * display name
     */
    "modelName"?: string;

    /**
     * "sdxl" | "zimage" | "wan"
     */
    "engine"?: string;
    "width"?: number;
    "height"?: number;

    /**
     * "square" | "portrait" | "landscape"
     */
    "formatCode"?: string;
    "numSteps"?: number;
    "guidanceScale"?: number;
    "scheduler"?: string;
    "clipSkip"?: number | null;
    "seed": number;
    "img2img"?: boolean;
    "strength"?: number;

    /**
     * RFC3339
     */
    "createdAt": string;
}

/**
 * GenerationRequest is the unified frontend → Go payload for both modes.
 * Mirrors imference-desktop/src/renderer/src/lib/types.ts GenerationParams.
 */
export interface GenerationRequest {
    "prompt": string;
    "negativePrompt"?: string;
    "width": number;
    "height": number;
    "numSteps": number;
    "guidanceScale": number;

    /**
     * Seed is a pointer so the JSON can carry null (= random) vs 0 (= explicit zero).
     */
    "seed"?: number | null;

    /**
     * Scheduler and ClipSkip are usually injected server-side from the selected
     * LocalModel's config (App.GenerateLocal) rather than set by the renderer,
     * but the fields exist so a caller can override. Empty/nil → engine default.
     */
    "scheduler"?: string;
    "clipSkip"?: number | null;

    /**
     * SourceImage enables img2img: a base64 source the engine denoises from
     * instead of pure noise. May be a data-URL ("data:image/png;base64,…") or
     * raw base64 — the sidecar client strips any data-URL prefix. Empty = text2img.
     */
    "sourceImage"?: string;

    /**
     * Strength is the img2img denoising strength (0 = keep source, 1 = ignore it).
     * Only meaningful with SourceImage set. 0/unset → engine default (0.75). In
     * img2img the output size is derived from the source image (Width/Height ignored).
     */
    "strength"?: number;
}

/**
 * GenerationResult is the unified Go → frontend response. Same shape for
 * cloud and local: image always arrives as base64 PNG/WebP so the React
 * side just sets `<img src="data:image/png;base64,..."/>` regardless of source.
 */
export interface GenerationResult {
    "imageBase64": string;
    "seed": number;

    /**
     * "cloud" | "local"
     */
    "source": string;

    /**
     * SavedPath is the absolute path to the auto-saved copy on disk. Empty
     * string when save failed (the failure is logged but doesn't fail the
     * generation — the in-memory base64 result is still usable).
     */
    "savedPath": string;

    /**
     * Meta is the generation metadata (same as the sidecar), so the freshly
     * generated image shows the same details in the UI as gallery images.
     */
    "meta"?: GenerationMeta | null;
}

/**
 * ImageRuntimeSettings tunes the SDXL backend (IMAGE_* env contract).
 */
export interface ImageRuntimeSettings {
    /**
     * "" / "auto" | cuda | cuda:N | mps | cpu
     */
    "device"?: string;

    /**
     * SDXL TAESDxl — ~10× faster VAE decode
     */
    "useTinyVae"?: boolean;

    /**
     * peak VRAM ↓ (≤8 GB), ~10–30% slower
     */
    "enableCpuOffload"?: boolean;

    /**
     * "" / "auto" / int
     */
    "maxGpuModels"?: string;

    /**
     * "" / "auto" / int
     */
    "maxCpuModels"?: string;
}

/**
 * ModelInfo is one entry from imference.com/api/models, trimmed to the fields
 * the desktop app uses. Doubles as the JSON contract for the frontend model
 * picker. Only models with a non-empty ModelURL can run locally — the rest are
 * cloud-only / proprietary (Flux, GPT-Image, Veo, Wan video, …).
 */
export interface ModelInfo {
    "modelCode": string;
    "name": string;
    "shortDescription": string;
    "mediumDescription": string;

    /**
     * thumbnail URL
     */
    "image": string;

    /**
     * downloadable .safetensors ("" = cloud-only)
     */
    "modelUrl": string;
    "promptPre": string;
    "promptNegative": string;
    "stepsDefault": number;
    "stepsMin": number;
    "stepsMax": number;
    "cfgDefault": number;
    "cfgMin": number;
    "cfgMax": number;

    /**
     * clip-skip
     */
    "skipDefault": number;
    "schedulerDefault": string;
    "formatCode": string;

    /**
     * BackendType is the internal engine backend, normalized from the catalog's
     * im_engine field: "sdxl" | "zimage" | "wan". (im_engine "external" and null
     * are filtered out upstream in cloud.ListModels — not locally runnable.)
     */
    "backendType"?: string;

    /**
     * BaseModel is the HF repo id of the shared base-components a backend needs
     * (Z-Image finetunes, e.g. "Tongyi-MAI/Z-Image-Turbo"). Empty for
     * self-contained SDXL single-file checkpoints. Resolved offline via the CDN.
     */
    "baseModel"?: string;

    /**
     * ShiftDefault is the Z-Image flow-matching shift (3.0≈480p, 5.0≈720p),
     * passed as backend_options={"shift": …}. Ignored by SDXL. 0 → engine default.
     */
    "shiftDefault"?: number;

    /**
     * Cost is the cloud run cost in credits (1 credit = $0.001). Local runs are
     * free. CanLocal/CanCloud declare where the model may run.
     */
    "cost": number;
    "canLocal": boolean;
    "canCloud": boolean;

    /**
     * Formats are the model's supported resolutions/ratios (im_format). Empty
     * when the catalog has none — the UI then falls back to generic formats.
     */
    "formats"?: FormatOption[] | null;

    /**
     * Catalog organization (im_model family/group) for sorting/grouping the list.
     */
    "order"?: number;
    "familyCode"?: string;
    "familyName"?: string;
    "groupCode"?: string;
}

/**
 * PythonInfo is the result of DetectPython: which interpreter we picked, and
 * its self-reported version. Used by the frontend's installer panel.
 */
export interface PythonInfo {
    "path": string;
    "version": string;
}

/**
 * SavedImage is one previously-generated image found on disk in the output
 * folder. The renderer fetches its bytes lazily via GetSavedImage(name) (base64
 * over the Wails bridge). Basic fields are parsed from the filename
 * "<YYYYMMDD-HHMMSS>_<source>_<seed>.<ext>"; Meta comes from the "<name>.json"
 * sidecar when present.
 */
export interface SavedImage {
    /**
     * file name (key for GetSavedImage / DeleteSavedImage)
     */
    "name": string;

    /**
     * "local" | "cloud" | …
     */
    "source": string;

    /**
     * 0 when unparseable
     */
    "seed": number;

    /**
     * absolute path on disk
     */
    "savedPath": string;

    /**
     * Width/Height let the renderer reserve the right aspect box before the bytes
     * load (masonry with any format). 0 when the header couldn't be read.
     */
    "width": number;
    "height": number;

    /**
     * Meta is the generation metadata from the sidecar JSON. Nil for images saved
     * before this feature (or hand-added files).
     */
    "meta"?: GenerationMeta | null;
}

/**
 * Settings persisted via internal/settings.Store. Empty strings are the
 * signal for "not configured" — the frontend offers the SettingsDialog when
 * any required field is empty.
 */
export interface Settings {
    "apiKey": string;
    "pythonPath": string;
    "sdxlPath": string;
    "cloudModel": string;

    /**
     * OutputDir overrides where generated images are auto-saved. When empty,
     * defaults to imagesink.DefaultDir() (typically <home>/Pictures/Imference).
     */
    "outputDir": string;

    /**
     * PaymentMode picks the cloud auth scheme: "bearer" (default; uses APIKey)
     * or "x402" (pays per request from the local wallet on Base mainnet).
     */
    "paymentMode": string;

    /**
     * WalletAddress is the public EVM address of the configured wallet,
     * mirrored here for display in the UI when the renderer hasn't unlocked
     * the keychain yet. The private key itself NEVER lives in this file —
     * it's in the OS keychain (Windows Credential Manager).
     */
    "walletAddress": string;

    /**
     * LocalModel is the currently-selected local model (chosen from the
     * imference catalog and downloaded to SDXLPath). Nil until the user picks
     * one. Its config drives local generation defaults — see App.GenerateLocal.
     */
    "localModel"?: ModelInfo | null;

    /**
     * EngineRuntime holds host-machine tuning for the engine (device, VAE mode,
     * offload, model-residency caps, WAN quantization). Applied as env vars when
     * the sidecar starts. NOT generation params — those live in the generation UI.
     */
    "engineRuntime": EngineRuntimeSettings;

    /**
     * CloudModelInfo is the full catalog entry for the selected cloud model
     * (CloudModel holds just its code, the value actually sent to the server).
     * Stored so the form selector can show the model's details and seed cloud
     * generation params (steps/cfg/resolution) the same way LocalModel does.
     * Nil until the user picks a cloud model from the form.
     */
    "cloudModelInfo"?: ModelInfo | null;
}

/**
 * SidecarStatus is broadcast via Wails events on the "sidecar:status" channel
 * every time the sidecar manager transitions states. The frontend uses the
 * `state` discriminator to render the header pill and to enable/disable the
 * Run Local button.
 */
export interface SidecarStatus {
    /**
     * idle | starting | ready | error | stopped
     */
    "state": string;
    "port"?: number;
    "device"?: string;
    "message"?: string;
}

/**
 * WalletInfo is what the renderer sees when it asks about the wallet
 * status. The private key is never exposed through this struct.
 */
export interface WalletInfo {
    /**
     * true if a key exists in the keychain
     */
    "configured": boolean;

    /**
     * checksummed hex (0x…) or ""
     */
    "address": string;

    /**
     * human string ("1.234"), atomic / 10^6
     */
    "balanceUSDC": string;

    /**
     * always "base-mainnet" in this POC
     */
    "network": string;
    "error"?: string;
}

/**
 * WanRuntimeSettings tunes the WAN video backend (WAN_* env contract). Applies
 * once the video backend is enabled; ignored by the image backends. The two
 * bool knobs are pointers because the engine defaults them to true — nil means
 * "leave at engine default", *false means the user explicitly disabled it.
 */
export interface WanRuntimeSettings {
    "device"?: string;

    /**
     * "" / "auto" | gguf_q8 | gguf_q6 | gguf_q5 | gguf_q4
     */
    "memoryProfile"?: string;

    /**
     * "" / int8 | none
     */
    "textEncoderQuant"?: string;

    /**
     * engine default true
     */
    "vaeTiling"?: boolean | null;

    /**
     * engine default true
     */
    "enableOffload"?: boolean | null;

    /**
     * "" / int
     */
    "maxResident"?: string;
}

/**
 * ZImageRuntimeSettings tunes the Z-Image backend (same IMAGE_* env contract).
 * No UseTinyVAE: Tiny VAE (TAESDxl) is SDXL-only and ignored by Z-Image.
 */
export interface ZImageRuntimeSettings {
    "device"?: string;
    "enableCpuOffload"?: boolean;
    "maxGpuModels"?: string;
    "maxCpuModels"?: string;
}
