// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is the on-wire shape exposed to the renderer. JSON tags match
 * frontend/src/lib/types.ts LogEntry.
 */
export interface Entry {
    /**
     * Monotonically increasing per Bus instance. The renderer uses this as a
     * React key and to detect dropped entries.
     */
    "id": number;

    /**
     * RFC3339 with millisecond precision
     */
    "timestamp": string;
    "level": Level;

    /**
     * free-form, e.g. "cloud", "sidecar", "app", "front"
     */
    "source": string;
    "message": string;
    "data"?: any;
}

/**
 * Level mirrors what the renderer panel colors by. "trace" is for chatty
 * inner-loop stuff we want available but not in the default view.
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelTrace = "trace",
    LevelInfo = "info",
    LevelWarn = "warn",
    LevelError = "error",
};
