// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {logbus} from '../models';

export function ClearLogs():Promise<void>;

export function DetectPython():Promise<types.PythonInfo>;

export function ExportWalletPrivateKey():Promise<string>;

export function GenerateCloud(arg1:types.GenerationRequest):Promise<types.GenerationResult>;

export function GenerateLocal(arg1:types.GenerationRequest):Promise<types.GenerationResult>;

export function GenerateWallet():Promise<string>;

export function GetEngineInfo():Promise<types.EngineInfo>;

export function GetLogs():Promise<Array<logbus.Entry>>;

export function GetSettings():Promise<types.Settings>;

export function GetSidecarStatus():Promise<types.SidecarStatus>;

export function GetWalletInfo():Promise<types.WalletInfo>;

export function ImportWallet(arg1:string):Promise<string>;

export function InstallEngine():Promise<void>;

export function LogFromFrontend(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function RefreshWalletBalance():Promise<string>;

export function RestartSidecar():Promise<void>;

export function SaveSettings(arg1:types.Settings):Promise<types.Settings>;
