// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DetectPython() {
  return window['go']['main']['App']['DetectPython']();
}

export function ExportWalletPrivateKey() {
  return window['go']['main']['App']['ExportWalletPrivateKey']();
}

export function GenerateCloud(arg1) {
  return window['go']['main']['App']['GenerateCloud'](arg1);
}

export function GenerateLocal(arg1) {
  return window['go']['main']['App']['GenerateLocal'](arg1);
}

export function GenerateWallet() {
  return window['go']['main']['App']['GenerateWallet']();
}

export function GetEngineInfo() {
  return window['go']['main']['App']['GetEngineInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSidecarStatus() {
  return window['go']['main']['App']['GetSidecarStatus']();
}

export function GetWalletInfo() {
  return window['go']['main']['App']['GetWalletInfo']();
}

export function ImportWallet(arg1) {
  return window['go']['main']['App']['ImportWallet'](arg1);
}

export function InstallEngine() {
  return window['go']['main']['App']['InstallEngine']();
}

export function LogFromFrontend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFromFrontend'](arg1, arg2, arg3, arg4);
}

export function RefreshWalletBalance() {
  return window['go']['main']['App']['RefreshWalletBalance']();
}

export function RestartSidecar() {
  return window['go']['main']['App']['RestartSidecar']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
